include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.gr.dart
    - lib/injection.config.dart
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
linter:
  rules:
    avoid_positional_boolean_parameters: false
